ingredients/urls.py
from django.urls import path
from .views import IngredientsList, IngredientsDetail, IngredientInput

app_name = "ingredients"

urlpatterns = [
    path("ingredients/list", IngredientsList.as_view(), name="ing"),
    path("ingredients/list/<pk>", IngredientsDetail.as_view(), name="ingd"),
    path("ingredients/new", IngredientInput.as_view(), name="ingredient-input"),
]

recipe_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, success


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("", include("ingredients.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("logged_out/", success, name="success"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, about, records, RecipeList, RecipeDetail, RecipeInput

app_name = "recipes"

urlpatterns = [
    path("", home, name="home"),
    path("about", about, name="about"),
    path("list", RecipeList.as_view(), name="recipe-list"),
    path("list/<pk>", RecipeDetail.as_view(), name="detail"),
    path("records", records, name="records"),
    path("recipe/new", RecipeInput.as_view(), name="recipe-input"),
]

ingredients/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.


class Ingredient(models.Model):
    units_of_measure = (
        ("tbsp", "Tablespoon"),
        ("tsp", "Teaspoon"),
        ("clove", "Clove"),
        ("slice", "Slice"),
        ("oz", "Ounce"),
        ("g", "Gram"),
        ("pc", "Piece"),
        ("half", "Half"),
        ("bag", "Bag"),
        ("cup", "Cup"),
        ("wedge", "Wedge"),
        ("pinch", "Pinch"),
        ("lb", "Pound"),
        ("lf", "Leaf"),
    )

    name = models.CharField(max_length=50)
    uom = models.CharField(
        max_length=20, default=None, blank=True, choices=units_of_measure
    )  # unit of measure
    pic = models.ImageField(upload_to="ingredients", default="drawing.svg")

    # builds an absolute path to a specific ingredient utlizing the name url param and the db primary of each ingredient.
    def get_absolute_url(self):
        return reverse("ingredients:ingd", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.name}"

recipes/models.py
from django.db import models
from ingredients.models import Ingredient
from django.shortcuts import reverse

# Create your models here.


class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.PositiveIntegerField(help_text="(minutes)")
    ingredients = models.ManyToManyField(Ingredient, blank=True)

    # builds an aboslute url to provide linkage to the specific recipe
    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"pk": self.pk})

    # access a query set of all ingredients to be able to display the ingredients on a details page.
    def get_ingredients(self):
        ingredient_objects = self.ingredients.all()
        return ingredient_objects

    # evaluates the difficulty of a recipe by checking ingredients length and cooking time against conditions.
    def calc_difficulty(self):
        new_difficulty = ""
        ingredients = self.get_ingredients()
        if self.cooking_time < 15 and len(ingredients) < 5:
            new_difficulty = "Easy"
        elif self.cooking_time < 15 and len(ingredients) >= 5:
            new_difficulty = "Medium"
        elif self.cooking_time >= 15 and len(ingredients) <= 5:
            new_difficulty = "Intermediate"
        elif self.cooking_time >= 15 and len(ingredients) >= 5:
            new_difficulty = "Hard"
        return new_difficulty

    def __str__(self):
        return f"{self.name}"

ingredients/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Ingredient

# Create your views here.


class IngredientsList(LoginRequiredMixin, ListView):
    model = Ingredient
    template_name = "ingredients/ing.html"


class IngredientsDetail(LoginRequiredMixin, DetailView):
    model = Ingredient
    template_name = "ingredients/ingd.html"


class IngredientInput(LoginRequiredMixin, CreateView):
    model = Ingredient
    template_name = "ingredients/ingredient_input.html"
    fields = ["name", "uom"]

ingredients/templates/ingredients/ing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'recipes/styles/style.css'%}">
  <title>Ingredients </title>
</head>

<body>
  <img src="{% static 'recipes/images/backsplash.jpg' %}" width="300" alt="bustling kitchen">
  <h1>Your Ingredients <img class="plate-svg" src="{% static 'recipes/images/dishBW.svg' %}" height="40" alt=""></h1>
  <a href="{% url 'ingredients:ingredient-input' %}">
    <h2>++ Ingredient </h2>
  </a>
  <div class="ingredients-list">
    {% for object in object_list %}
    <div class="recipe-brief">
      <a href="{{object.get_absolute_url}}">
        <h2>{{object.name}}</h2>
      </a>
    </div>
    {% endfor %}
  </div>
</body>

</html>
{% endblock content %}

ingredients/templates/ingredients/ingd.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'recipes/styles/style.css'%}">
    <title>{{object.name}}</title>
</head>

<body>
    <img src="{% static 'ingredients/images/spices.jpg' %}" width="400" alt="spices array">
    <h2>{{object.name}}</h2>
    <h2>Common Unit of Measure: [{{object.uom}}]</h2>
    <a href="{% url 'ingredients:ing' %}">Back to ingredients</a>
    <a href="{% url 'recipes:recipe-input' %}">++ Recipe</a>
    <a href="{% url 'ingredients:ingredient-input' %}">++ Ingredient</a>
    <br>
    <h2>
        Used in :
    </h2>
    <div class="used-in-container">
        {%if object.recipe_set.all %}
        {% for object in object.recipe_set.all %}
        <div class="recipe-brief">
            <a href="{{object.get_absolute_url}}">{{ object}}</a>
        </div>
        {%endfor%}
        {% else %}
        <p>no usage yet.</p>
        {% endif %}
    </div>

</body>

</html>
{% endblock content %}

ingredients/templates/ingredients/ingredient_input.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'recipes/styles/style.css'%}">
    <title>Ingredient Input</title>
</head>

<body>
    <h2>New Ingredient</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p}}
        <button class="search-btn" type="submit">Save Ingredient</button>
    </form>
</body>

</html>
{% endblock content %}