ingredients/urls.py
from django.urls import path
from .views import IngredientsList, IngredientsDetail, IngredientInput

app_name = "ingredients"

urlpatterns = [
    path("ingredients/list", IngredientsList.as_view(), name="ing"),
    path("ingredients/list/<pk>", IngredientsDetail.as_view(), name="ingd"),
    path("ingredients/new", IngredientInput.as_view(), name="ingredient-input"),
]

recipe_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, success


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("", include("ingredients.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("logged_out/", success, name="success"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, about, records, RecipeList, RecipeDetail, RecipeInput

app_name = "recipes"

urlpatterns = [
    path("", home, name="home"),
    path("about", about, name="about"),
    path("list", RecipeList.as_view(), name="recipe-list"),
    path("list/<pk>", RecipeDetail.as_view(), name="detail"),
    path("records", records, name="records"),
    path("recipe/new", RecipeInput.as_view(), name="recipe-input"),
]

templates/base.html
{% load static %}

<body>
    <header>
        <a href="{% url 'recipes:home' %}">Home</a>
        <a href="{% url 'recipes:recipe-list' %}">Recipes</a>
        <a href="{% url 'ingredients:ing' %}">Ingredients</a>
        <a href="{% url 'recipes:records' %}">Records</a>
        <a href="{% url 'recipes:about' %}">About</a>
    </header>

</body>
<br>
{% block content %}
{% endblock content %}